const analyzer=new GeometryAnalyzer(); let selected=surnames.find(s=>s.glyph==='王')||surnames[0]; let activeBudget=1;
const renderScale=240/dataset.parameters.sizeMm;
const $=id=>document.getElementById(id);
function download(name,body,type){const url=URL.createObjectURL(new Blob([body],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function renderNames(){const q=$('search').value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');const list=surnames.filter(s=>(s.glyph+s.pinyin).toLowerCase().includes(q));$('count').textContent=list.length;$('names').innerHTML=list.length?list.map(s=>`<button class="surname ${s.index===selected.index?'active':''}" data-index="${s.index}" aria-label="${s.glyph} ${s.pinyin}" aria-pressed="${s.index===selected.index}"><strong>${s.glyph}</strong><span>${s.pinyin}</span></button>`).join(''):'<p>沒有符合的姓氏。</p>';document.querySelectorAll('.surname').forEach(b=>b.onclick=()=>{selected=surnames.find(s=>s.index===+b.dataset.index);renderNames();render();});}
function lineD(points){return 'M '+points.map(([x,y])=>`${x*renderScale+30},${y*renderScale+30}`).join(' L ');}
function svg(c){if(!c.valid)return '<div class="unavailable">目前尺寸與寬度下未找到有效解。</div>';
 return `<svg viewBox="0 0 300 300" role="img" aria-label="${selected.glyph}：${c.loops} 條已驗證閉合輪廓"><rect width="300" height="300" fill="#f8faf5"/><path d="${c.shapePath}" fill="#dbe4d7" fill-rule="evenodd"/>${$('original').checked?`<path d="${selected.originalPath}" fill="none" stroke="#adb6a6" stroke-width=".9" stroke-dasharray="2 2"/>`:''}${$('paths').checked?c.paths.map((p,i)=>`<path class="route" d="${p}" fill="none" stroke="${['#216b52','#7456a4','#28668c'][i%3]}" stroke-width="1.5" stroke-linejoin="round"/>`).join(''):''}${$('bridges').checked?c.edits.map((e,i)=>`<g><path d="${lineD(e.points)}" fill="none" stroke="${e.kind==='bridge'?'#e59539':'#cf5c70'}" stroke-width="${e.widthMm*renderScale}" opacity=".65" stroke-linecap="round"/><text x="${e.points[0][0]*renderScale+30}" y="${e.points[0][1]*renderScale+26}" font-size="8" fill="#763f30">${i+1}</text></g>`).join(''):''}</svg>`;
}
function render(){const cs=analyzer.analyze(selected),r=recommend(cs,+$('balance').value);$('selected-name').textContent=selected.glyph;$('pinyin').textContent=selected.pinyin;$('preference').textContent=`重合度 ≥ ${r.fidelityFloor.toFixed(2)}%`;$('native-info').textContent=`原字：${selected.native.components} 個連通部件 ＋ ${selected.native.holes} 個內孔 ＝ ${selected.native.loops} 條閉合輪廓`;
 $('candidates').innerHTML=cs.map(c=>`<article class="candidate ${r.candidate?.budget===c.budget?'recommended':''}" data-card="${c.budget}"><div class="card-title"><b>最多 ${c.budget} 圈</b><span>${r.candidate?.budget===c.budget?'✦ 推薦':c.valid?`實際 ${c.loops} 圈`:'未找到解'}</span></div>${svg(c)}${c.valid?`<div class="metrics"><div><span>字形重合度 IoU</span><b>${(c.metrics.iou*100).toFixed(2)}%</b></div><div class="bar"><i style="width:${c.metrics.iou*100}%"></i></div><div><span>閉合／無自交</span><b>通過 · ${c.loops} 圈</b></div><div class="measure-row">路徑 ${c.metrics.pathLengthMm.toFixed(1)} mm<br>細筆面積 ${(c.metrics.thinInkFraction*100).toFixed(2)}%<br>${c.edits.filter(e=>e.kind==='bridge').length} 橋接 · ${c.edits.filter(e=>e.kind==='cut').length} 切口</div><div class="bridge-count"><button data-animate="${c.budget}">▶ 走一遍</button><button data-svg="${c.budget}">↓ SVG</button></div></div>`:''}</article>`).join('');
 const c=r.candidate;$('recommendation').innerHTML=`<div class="rec-icon">${c?'✦':'○'}</div><div><div class="eyebrow">${c?'已找到的最少圈數':'目前門檻下沒有合格方案'}</div><h3>${c?`${selected.glyph}：${c.loops} 圈${c.edits.length===0?'，原字不用改動':''}`:'保留更多圈數，或降低保真門檻。'}</h3><p>${c?`字形重合度 ${(c.metrics.iou*100).toFixed(2)}%，保留原筆畫面積 ${(c.metrics.retainedInk*100).toFixed(2)}%。${c.edits.length} 處幾何修改；每條輸出輪廓均閉合且無自交。`:'這不是「一定不能一圈」；現有求解結果未同時滿足重合度、橋接寬度與細筆面積 ≤ 2% 的條件。'}</p></div>`;
 $('inspection').textContent='按「走一遍」可看到實際輸出輪廓的連續走線。';
 document.querySelectorAll('[data-animate]').forEach(b=>b.onclick=()=>{activeBudget=+b.dataset.animate;if(!$('paths').checked){$('paths').checked=true;render();}const candidate=cs.find(c=>c.budget===activeBudget);const routes=document.querySelectorAll(`[data-card="${activeBudget}"] .route`);let delay=0;routes.forEach(p=>{const length=p.getTotalLength();p.animate([{strokeDasharray:`${length} ${length}`,strokeDashoffset:length},{strokeDasharray:`${length} ${length}`,strokeDashoffset:0}],{duration:2600,delay,fill:'backwards'});delay+=2600;});$('inspection').textContent=`${selected.glyph}：${candidate.loops} 條閉合線，依序播放；${candidate.loops>1?`需要 ${candidate.loops-1} 次換線。`:'全程單一閉合路徑，不需換線。'} 橋接和切口均已納入實際輪廓。`;});
 document.querySelectorAll('[data-svg]').forEach(b=>b.onclick=()=>{const c=cs.find(c=>c.budget===+b.dataset.svg);const path=c.pathsMm.map(ps=>'M '+ps.slice(0,-1).map(p=>p.join(',')).join(' L ')+' Z').map(d=>`<path d="${d}"/>`).join('');download(`${selected.glyph}-${c.loops}loops.svg`,`<svg xmlns="http://www.w3.org/2000/svg" width="${dataset.parameters.sizeMm+4}mm" height="${dataset.parameters.sizeMm+4}mm" viewBox="-2 -2 ${dataset.parameters.sizeMm+4} ${dataset.parameters.sizeMm+4}"><title>${selected.glyph} ${c.loops} closed contour paths; millimetres</title><g fill="none" stroke="black" stroke-width="0.1">${path}</g></svg>`,'image/svg+xml');});
}
$('settings').textContent=`字型：${dataset.font}。字形最大邊 ${dataset.parameters.sizeMm} mm；橋寬 ${dataset.parameters.bridgeWidthMm} mm；切口 ${dataset.parameters.cutWidthMm} mm；線寬檢查 ${dataset.parameters.lineWidthMm} mm。細筆面積是形態學開運算估計的過窄區域，不是列印成功率。`;
$('search').oninput=renderNames;['balance','bridges','paths','original'].forEach(id=>$(id).oninput=render);$('export').onclick=()=>download('traditional-surname-topology.json',JSON.stringify({...dataset,preference:+$('balance').value,recommendations:surnames.map(s=>({glyph:s.glyph,...recommend(s.candidates,+$('balance').value)}))},null,2),'application/json');renderNames();render();
